### PR TITLE
Master

### PR DESCRIPTION
**Pull request by hazulu**
Must Reference MySql.Data.Entity.EF6, MySql.Data, MySql.Web

MySQL DB Connection

localhost, port 3306, db: inspire, user: root, pass:,

Use DropCreateDatabaseIfModelChangesAlways<>() to force seed the database.

### CODE REVIEW

**Comment by Aeirex** [comment]
`An unhandled exception of type 'System.Data.Entity.Core.ProviderIncompatibleException' occurred in EntityFramework.dll`

The Map Simulator is causing an issue when I try to run it.

**Comment by hazulu** [comment]
Are you sure your DB is set up properly? Are the connection settings to your DB correct? Can you force seed the DB?

**Comment by Aeirex** [comment]
@hazulu I didn't really mess with the database system at all, what I setup was another repo using a slightly different codebase. It uses MySQL where this uses something else. If there's missing data, commit the default code to make it work right when you pull it. That means the database should come preconfigured when you pull.

**Comment by Aeirex** [comment]
Map Simulator is still broken. Going to look into it later.

**Comment by Aeirex** [comment]
This has been merged into 'working'.

**Pull request closed without merging**
